# Generated by Django 3.2.25 on 2024-10-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20241011_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('rack_size', models.IntegerField(blank=True, null=True)),
                ('memory', models.CharField(blank=True, max_length=255, null=True)),
                ('disk', models.CharField(blank=True, max_length=255, null=True)),
                ('nics', models.IntegerField(blank=True, null=True)),
                ('processor_model', models.CharField(blank=True, max_length=255, null=True)),
                ('processor_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('processor_count', models.IntegerField(blank=True, null=True)),
                ('cards', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('outlet_count', models.IntegerField(blank=True, null=True)),
                ('estimated_cost', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('visualization_color', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet_type', models.CharField(blank=True, max_length=255, null=True)),
                ('power_supply_count', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('processor_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('processor_socket_count', models.IntegerField(blank=True, null=True)),
                ('power_supply_slot_count', models.IntegerField(blank=True, null=True)),
                ('power_consumption', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('variant', models.CharField(blank=True, max_length=255, null=True)),
                ('version_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('architecture', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('processor_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('processor_model', models.CharField(blank=True, max_length=255, null=True)),
                ('processor_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('processor_socket_count', models.IntegerField(blank=True, null=True)),
                ('processor_count', models.IntegerField(blank=True, null=True)),
                ('physical_memory', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_memory_sizes', models.CharField(blank=True, max_length=255, null=True)),
                ('os_memory', models.CharField(blank=True, max_length=255, null=True)),
                ('swap', models.CharField(blank=True, max_length=255, null=True)),
                ('power_supply_count', models.IntegerField(blank=True, null=True)),
                ('console_type', models.CharField(blank=True, max_length=255, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=255, null=True)),
                ('kernel_version', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('processor_core_count', models.IntegerField(blank=True, null=True)),
                ('os_processor_count', models.IntegerField(blank=True, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('virtualarch', models.CharField(blank=True, max_length=255, null=True)),
                ('vmimg_size', models.IntegerField(blank=True, null=True)),
                ('vmspace_used', models.IntegerField(blank=True, null=True)),
                ('used_space', models.IntegerField(blank=True, null=True)),
                ('avail_space', models.IntegerField(blank=True, null=True)),
                ('os_virtual_processor_count', models.IntegerField(blank=True, null=True)),
                ('hardware_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.hardwareprofile')),
                ('operating_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.operatingsystem')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.status')),
            ],
        ),
    ]
