# Generated by Django 3.2.25 on 2024-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_hardwareprofile_node_operatingsystem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='centrify_zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
