# Generated by Django 3.2.25 on 2024-10-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_node_centrify_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(default='needsapproval', max_length=20),
        ),
    ]
