# Generated by Django 3.2.25 on 2024-10-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='domain',
            field=models.CharField(default='corp.pvt', max_length=255),
        ),
    ]
