# Generated by Django 3.2.25 on 2024-10-16 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_node_disk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='myapp.deployment'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
