# Generated by Django 3.2.25 on 2024-10-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_deployment_builtby'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='approval_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
