# Generated by Django 3.2.25 on 2024-10-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_deployment_approval_alert_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
