# Generated by Django 3.2.25 on 2024-10-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_node_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
